# version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: qindia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: qindia
      POSTGRES_PASSWORD: qindia
      POSTGRES_DB: qindia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: qindia-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data: